server:
  port: 8091
spring:
  application:
    name: core-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        前端登录时，转到认证
        - id: authentication-server-auth
          uri: lb://authentication-server
          predicates:
            - Path=/user/center/user/login
          filters:
            - RewritePath=/user/center/user/login,/authenticate
#        前端退出登录时，禁用token
        - id: authentication-server-disable
          uri: lb://authentication-server
          predicates:
            - Path=/user/op/logout
          filters:
            - RewritePath=/user/op/logout,/authenticate/disable
#        转发至用户中心
        - id: user-center-server
          uri: lb://user-center-server
          predicates:
            - Path=/user/center/**
#        基础数据
        - id: basedata-service-server
          uri: lb://basedata-service-server
          predicates:
            - Path=/nontax/basedata/**
#        财政票据平台
        - id: nontax-financial-service-server
          uri: lb://nontax-financial-service-server
          predicates:
            - Path=/nontax/financial/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
