app:
  version: 1.0.0
server:
  port: 8083
  servlet:
    context-path: /user/center
spring:
  cache:
    type: none
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://114.55.137.13:9000/user_center?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 1200000
      max-lifetime: 1800000
      pool-name: user_center_pool
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: user-center-server
swagger:
  title: user-center-server
  description: api for user-center-server
  version: 0.0.1
  apiBasePackage: com.hyd.user.center.web
pagehelper:
  reasonable: true
  support-methods-arguments: true

# actuator配置
info: # info下的信息可以自定义
  app:
    name: user-center
    version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*' # 打开所有的监控点
      base-path: /monitor # 启用单独的url地址来监控 Spring Boot 应用
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true # 启用接口关闭 Spring Boot

