app:
  version: 1.0.0
server:
  port: 8081
  servlet:
    context-path: /nontax/financial
spring:
  datasource:
    url: jdbc:mysql://114.55.137.13:9000/nontax_financial?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.137.13:9003
  application:
    name: nontax-financial-service-server
swagger:
  title: nontax-financial
  description: api for nontax-financial
  version: 0.0.1
  apiBasePackage: com.hyd.financial.web

